### ISSUE TITLE
No about:config?

### ISSUE THREAD

**Issue by jekv2** [fork-maintainers/iceraven-browser#870]
There is no about:config?

i get invalid address.

https://i.ibb.co/bjhhjZZH/Screenshot-20250308-150445.png

**Comment by zkvsky** [comment]
Same issue with 2.29.0.

**Comment by jekv2** [comment]
> Same issue with 2.29.0.

i just tested, bout to post that it's Iceraven: 2.29.0

👍 yup

**Comment by jekv2** [comment]
2.28.0 is sweet. i will dump slimsocial now. wish i could open iceraven and choose what ever many profiles and open it up more than one at once. 

should how sweet facebook slides n the resolution too. way dif.

i use 4 browsers. I believe when i get time, i will switch iceraven to my main.

reason i like about config

general.useragent.override


Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0

https://i.ibb.co/ZpWvkDyZ/Screenshot-20250308-160243-1.png

**Comment by jrichard326** [comment]
Same here on 2.29.0, however,
chrome://geckoview/content/config.xhtml

Still works. Thank you for all of your work on this browser.

**Comment by Kernel-su-source** [comment]
I have the same issue with 2.29, I had to go back to the previous version

**Comment by jekv2** [comment]
> Same here on 2.29.0, however, chrome://geckoview/content/config.xhtml
> 
> Still works. Thank you for all of your work on this browser.

the chrome link takes it to duckduckgo

https://i.ibb.co/ccznCZHn/Screenshot-20250310-120113.png

**Comment by jrichard326** [comment]
It didn't work for you because FF/ice raven removed the chrome:// part of the URL and forces the default search engine. So, you need to make sure the complete URL is in the address bar.  If you bookmark the correct address it works as well

**Comment by akliuxingyuan** [comment]
looks like something is broken, will take a look when I get time.

**Comment by jekv2** [comment]
> It didn't work for you because FF/ice raven removed the chrome:// part of the URL and forces the default search engine. So, you need to make sure the complete URL is in the address bar. If you bookmark the correct address it works as well

i cannot add chrome://geckoview/content/config.xhtml to bookmarks either, no add custome link.

**Comment by jrichard326** [comment]
![Image](https://github.com/user-attachments/assets/efe2b71c-d5ec-4bc0-973e-00d29523871f)

It works fine here, just like in FF stable.
In any case, the developer is aware of the issue and is working on it.

**Comment by jvvcn7** [comment]
Yeah this a bummer, looking forward to the fix. Thanks all.

**Comment by jekv2** [comment]
> ![Image](https://github.com/user-attachments/assets/efe2b71c-d5ec-4bc0-973e-00d29523871f)
> 
> It works fine here, just like in FF stable. In any case, the developer is aware of the issue and is working on it.

dunno how u r makin it work.
https://i.ibb.co/rRpBd5mm/Screenshot-20250312-074302.png

**Comment by kairusds** [comment]
> > ![Image](https://github.com/user-attachments/assets/efe2b71c-d5ec-4bc0-973e-00d29523871f)
> > It works fine here, just like in FF stable. In any case, the developer is aware of the issue and is working on it.
> 
> dunno how u r makin it work. https://i.ibb.co/rRpBd5mm/Screenshot-20250312-074302.png

Just paste the full url in the address bar

**Comment by jekv2** [comment]
> > > ![Image](https://github.com/user-attachments/assets/efe2b71c-d5ec-4bc0-973e-00d29523871f)
> > > It works fine here, just like in FF stable. In any case, the developer is aware of the issue and is working on it.
> > 
> > 
> > dunno how u r makin it work. https://i.ibb.co/rRpBd5mm/Screenshot-20250312-074302.png
> 
> Just paste the full url in the address bar

i did, take a look at the screenshot link.

**Comment by jekv2** [comment]
> > > > ![Image](https://github.com/user-attachments/assets/efe2b71c-d5ec-4bc0-973e-00d29523871f)
> > > > It works fine here, just like in FF stable. In any case, the developer is aware of the issue and is working on it.
> > > 
> > > 
> > > dunno how u r makin it work. https://i.ibb.co/rRpBd5mm/Screenshot-20250312-074302.png
> > 
> > 
> > Just paste the full url in the address bar
> 
> i did, take a look at the screenshot link.

i got it, i highlighted the text link, hit search, opened to duckduckgo, full link is url, hit enter, bam.

https://i.ibb.co/G3FN3mxg/Screenshot-20250313-083725.png

**Comment by LastTacoMaker** [comment]
What's bizarre is that, on the announcements for when  2.29.0  was released, **about:config** support was the **_FIRST_** feature they chose to list:

![Image](https://github.com/user-attachments/assets/bb0439c2-ad89-43e7-aab0-614cba76c7b4)

How could this have been missed? Something is weird about this issue. Instinctually, I feel it was disabled intentionally. Something must have caused them to consciously choose to block it - as it is being _blocked_.

**Comment by akliuxingyuan** [comment]
fixed in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.30.0

**Comment by catbabylon** [comment]
Although it is certainly fixed when accessing directly, I noticed that about:config still doesn't show in the list on about:about
