### ISSUE TITLE
[Feature Request]: Grey bar in the status-bar/notch area during fullscreen video playback

### ISSUE THREAD

**Issue by ramansg** [fork-maintainers/iceraven-browser#931]
### Feature Summary

![Image](https://github.com/user-attachments/assets/77050d1f-fcd2-4333-840a-94877c816e1c)

As visible in the attached image above, during playback of a video in fullscreen, there is a persistent grey bar in the status bar area that extends to the camera notch. It also persists in the private mode, but the grey bar changes to purple. (couldn't get a screenshot).

### Feature Research

I have consistently observed it over years on firefox and on icecraven since months ago. Screenshot above as proof. Also present as purple in private mode. (Unable to screenshot)

It breaks the immersion in fullscreen playback and is a visual distraction.

### Alternative Solution

Instead of grey/purple, the colour could be changed to black.

### Target beneficiaries

Every fullscreen video watcher will benefit. Especially when this visual distraction isn't present in chrome/edge browser, it will also remove one obstacle in adopting this browser.

**Comment by reigneil** [comment]
@ramansg maybe we have similar issue try to downgrade your browser to:
`Iceraven: 2.26.0
Fenix: 133.0`
with this version i was not able to reproduced that (grey/purple) bar at fullscreen video playback
although i was hoping it will be fixed beyond that version..

**Comment by ramansg** [comment]
> try to downgrade your browser to: `Iceraven: 2.26.0 Fenix: 133.0` with this version i was not able to reproduce that

sorry for late reply, I fear downgrading will delete some of my browser data, so i'd rather hope and wait for a fix in future version

**Comment by akliuxingyuan** [comment]
It's should be fixed in upstream, please verify in latest Iceraven.

**Comment by reigneil** [comment]
sadly it aint fixed the issue for me.
it might be due to i guess im running android 11
like what the op says using chrome does not create this problem. and for weird reason the only version that works for me was v133 anything higher or below that could show that issue.

![Image](https://github.com/user-attachments/assets/49efb7a6-4d75-4e88-ba89-27e513c4d09a)

note that this issue exist on official firefox release.
as a work around maybe atlease darkened that notch area or finding out what is change on v133 to make it fix

**Comment by ramansg** [comment]
hey @akliuxingyuan , Just tested v2.35.0, and this issue is still present for me, might be because of the same reason as @reigneil that my device is a11.
